### ISSUE TITLE
Can you provide the training config?

### ISSUE THREAD

**Issue by Sxx1995** [ZzZZCHS/WS-3DVG#1]
I simply trained the model with the provided command " python scripts/joint_scripts/train.py" but got bad performance. Can you please provide me the detailed training configuration used in your training?

**Comment by ZzZZCHS** [comment]
Hi,

I trained the default settings of the current code before and achieved similar results as the ones provided in our paper. However, I am currently on vacation and facing difficulties connecting to my lab's server. Therefore, I am not sure what is causing your problem at the moment. I will give you my training log when I return.

Could you please provide me with your training log so that I can check the problem for you now?

**Comment by ZzZZCHS** [comment]
Hi Sxx1995,

I have now uploaded my training log in [Google Drive](https://drive.google.com/drive/folders/18o-IYQj9RPo22tgkHWYEQ1gYKDkazjyR?usp=sharing). In this run, the best performance on ScanRefer is 27.08/21.68. You can check the training config in the log.

<img width="580" alt="Screenshot 2024-01-04 at 9 41 16 PM" src="https://github.com/ZzZZCHS/WS-3DVG/assets/50910784/89fce142-7c8f-485c-8740-5bc96c1eb961">
